version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    command: tail -f /dev/null
    ports:
      - "8082:8080"
      - "35731:35729"
    volumes:
      - .:/usr/src/app:cached
    tty: true
